# A kubernetes Job that prints hello world
# and exits 0
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo "Hello, World!"']
      restartPolicy: Never
  backoffLimit: 4
